3mf node export
elalish/manifold pull request #517
Opened 2023-08-04 04:47 UTC by elalish

This makes our 3MF export consistent with our GLB export when `GLTFNode` is used, creating the same scene hierarchy with mesh reuse. No materials yet, but we do include object names and a proper header. 

This is blocked on https://github.com/hrgdavor/jscadui/pull/37, which will need an npm release for us.

2023-08-04 04:48 UTC, elalish commented
FYI @hrgdavor

2023-08-04 08:30 UTC, hrgdavor commented
just released `@jscadui/3mf-export/0.4.0` with changes incorporated.

I would like to point out that the export supports embedding a thumbnail, it would be cool if manifold would take advantage of that when exporting. There is example of it in the repo called testGen.js

2023-08-04 08:46 UTC, hrgdavor requested changes
version change needed

2023-08-04 08:46 UTC, hrgdavor commented on bindings/wasm/examples/package.json
> +    "@jscadui/3mf-export": "^0.4.0",
needs to be 0.4.1

2023-08-04 15:05 UTC, elalish commented
> there was a small bug introduced in `to3dmodel` ... parameter `...header` was changed to `header` which is not correct ... header is supposed to pickup all other keys from the function options param, and fwd it.

Hmm, I actually changed that intentionally in order to make the header parameters work (and tested it). Since `header` is passed as a complete object to `pushHeader`, if you use `...` you don't actually end up with a variable called `header` at all (you only get it's sub-members individually).

2023-08-04 16:37 UTC, hrgdavor commented
What does your calling the function look like ? This dotted variant works in the test script within the package

2023-08-05 13:11 UTC, hrgdavor commented
@elalish I checked the header parameter and the types you proposed. I agree with separating the header object instead of mixing the keys in the options.

v0.4.2 is published that is aligned with your call to `to3dmodel` that I found more practical. I also separated out `to3dmodelSimple` variant of the function for cases where I have just set of meshes without a hiararchy (that is usual for jscad).
I transfered the proposed interfaces to jsdoc format with minor tweaks.

2023-08-05 21:33 UTC, elalish commented
@hrgdavor Awesome, thank you! I'll get back to this shortly, but I need to go to a wedding first.

2023-08-08 05:31 UTC, elalish commented
@pca006132 Did you say something about a problem with the windows TBB build?

2023-08-08 05:32 UTC, pca006132 commented
yes, maybe we can disable it for now until I find a way to fix it.

2023-08-08 05:35 UTC, elalish commented
It's already marked "not required", so I guess it's fine for the moment. Ideally we should scope down this CI list a bit (if we go full TBB) and make all the remaining ones required.

2023-08-08 05:35 UTC, merged