Godot patches
elalish/manifold pull request #93
Opened 2022-04-19 12:22 UTC by fire

Here are the changes I did. Pushing for cicd testing.

2022-04-19 12:28 UTC, fire commented on test/data/Csaszar.ply
> +ply
These changes are probably not necessary. The test source changes aren't either.

2022-04-19 12:29 UTC, fire commented on test/polygon_test.cpp
> +    float xMin = std::numeric_limits<float>::infinity();
Whitespace.

2022-04-19 12:29 UTC, fire commented on tools/perf_test.cpp
> +  for (int i = 0; i < 3; ++i) {
?

2022-04-19 14:12 UTC, fire commented
@elalish `1 workflow awaiting approval` Can you approve the workflow?

2022-04-19 15:00 UTC, elalish requested changes

2022-04-19 15:01 UTC, elalish commented
CUDA compilation work on my machine, so i may just need to update the version of CUDA on the CI.

2022-04-19 21:53 UTC, fire commented on manifold/src/impl.cu
> +  std::vector<int> comp2tri(numNodes, -1);
I'm not sure how this worked at all.

2022-04-19 22:28 UTC, fire commented on manifold/src/impl.cu
> +  std::vector<int> comp2tri(numNodes, -1);
I think it worked by creating a component array that is semi-empty except for the components. 

A component has an index (unused) in the array and also the value of its root.

2022-04-19 22:45 UTC, fire commented on manifold/src/impl.cu
> +  std::vector<int> comp2tri(numNodes, -1);
Expected to have been given a list of { root tri, a vector of neighbours }.

2022-04-20 14:51 UTC, fire commented
Rebased. 

Needs cicd approval.

Also, do geometry tests run on github actions?

2022-04-21 06:58 UTC, elalish commented
Is this needed anymore now that #92 is merged?

2022-04-21 13:59 UTC, fire commented
Let me check.

2022-04-21 14:02 UTC, fire commented
@elalish Cicd approval required.

2022-04-21 16:19 UTC, fire commented on manifold/include/manifold.h
> +#include "../../utilities/include/structs.h"
Not necessary.

2022-04-21 16:32 UTC, elalish approved these changes

2022-04-21 16:48 UTC, merged